version: '3'
services:
  cifer:
    network_mode: "host"
    restart: always
    build: .
    container_name: 'cifer'
    working_dir: '/root/'
    tty: true
    volumes:
      - ../../../ipeq:/root/ipeq
    deploy:
      resources:
        limits:
          cpus: '8'
          memory: 128g
